name: Modify README

on:
  push:
    branches:
      - master

jobs:
  modify-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify README
        run: |
          echo "Success!!!😊" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "<>"
          git add .
          git commit -m "Update README with a message by GitHub Action"
          git push
